from setuptools import setup, find_packages

setup(
    name="query-adaptive-hybrid-search",
    version="0.1.0",
    description="Adaptive hybrid retrieval with per-query BM25+dense fusion via QDAP (Posokhov et al., 2026)",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://doi.org/10.3390/make8040091",
    keywords=[
        "information-retrieval",
        "hybrid-search",
        "semantic-search",
        "bm25",
        "dense-retrieval",
        "multilingual-nlp",
        "contrastive-learning",
        "miracl",
        "mteb",
        "pytorch",
        "transformers",
        "question-answering",
        "retrieval-augmented-generation",
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Text Processing :: Linguistic",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "License :: Other/Proprietary License",
    ],
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[
        "torch>=2.0",
        "transformers>=4.36",
        "datasets>=2.14",
        "faiss-cpu>=1.7.4",
        "rank_bm25>=0.2.2",
        "numpy>=1.24",
        "scipy>=1.10",
        "scikit-learn>=1.3",
        "tqdm>=4.65",
        "hydra-core>=1.3",
        "omegaconf>=2.3",
    ],
    extras_require={
        "gpu": ["faiss-gpu>=1.7.4"],
        "logging": ["wandb"],
    },
)
